import sys


# ============================================================
# File handling
# ============================================================

def read_bytes_lines(path):
    """
    Read a file as raw bytes and split it into lines using
    the newline byte b'\\n'.

    Important:
    - We do NOT use text mode.
    - \\r is kept as part of the line.
    - A final empty piece caused by a trailing \\n is removed.
    """

    try:
        with open(path, "rb") as f:
            data = f.read()
    except (OSError, IOError):
        return None

    lines = data.split(b"\n")

    # A final newline does not create an extra empty line.
    if lines and lines[-1] == b"":
        lines.pop()

    return lines


# ============================================================
# Myers Diff
# ============================================================

def myers_diff(a, b):
    """
    Myers shortest edit script.

    a and b can contain ANY comparable objects:
        - bytes objects for Part A
        - strings/code points for Part B

    Returns:
        ("equal", item)
        ("delete", item)
        ("insert", item)

    The number of delete + insert operations is minimal.
    """

    n = len(a)
    m = len(b)

    # --------------------------------------------------------
    # Fast cases
    # --------------------------------------------------------

    if n == 0:
        return [("insert", item) for item in b]

    if m == 0:
        return [("delete", item) for item in a]

    if a == b:
        return [("equal", item) for item in a]

    # --------------------------------------------------------
    # V[k] = furthest x-coordinate reached on diagonal k
    #
    # k = x - y
    #
    # We use a dictionary because k can be negative.
    # --------------------------------------------------------

    v = {1: 0}

    # Store V after every D layer.
    trace = []

    max_d = n + m

    for d in range(max_d + 1):

        for k in range(-d, d + 1, 2):

            # ------------------------------------------------
            # Decide where this path comes from.
            #
            # k + 1 -> insertion
            # k - 1 -> deletion
            # ------------------------------------------------

            if k == -d:
                # We cannot come from k - 1.
                x = v.get(k + 1, 0)

            elif k == d:
                # We cannot come from k + 1.
                x = v.get(k - 1, 0) + 1

            elif v.get(k - 1, -1) < v.get(k + 1, -1):
                # Coming from k + 1 reaches farther.
                x = v.get(k + 1, 0)

            else:
                # Coming from k - 1 reaches farther.
                x = v.get(k - 1, 0) + 1

            y = x - k

            # ------------------------------------------------
            # Snake:
            #
            # Continue diagonally while the elements are equal.
            # ------------------------------------------------

            while x < n and y < m and a[x] == b[y]:
                x += 1
                y += 1

            # Store the furthest x for this diagonal.
            v[k] = x

            # ------------------------------------------------
            # If we reached the bottom-right corner, the
            # shortest edit script has been found.
            # ------------------------------------------------

            if x >= n and y >= m:

                # IMPORTANT:
                # Save this completed D layer before backtracking.
                trace.append(v.copy())

                return backtrack(a, b, trace, d)

        # ----------------------------------------------------
        # Save V AFTER this entire D layer has been processed.
        # ----------------------------------------------------

        trace.append(v.copy())

    return []


def backtrack(a, b, trace, final_d):
    """
    Reconstruct the shortest edit script from the trace
    generated by Myers' forward algorithm.
    """

    x = len(a)
    y = len(b)

    operations = []

    # Work backwards from (N, M).
    for d in range(final_d, 0, -1):

        v = trace[d]

        k = x - y

        # ----------------------------------------------------
        # Determine which previous diagonal we came from.
        # ----------------------------------------------------

        if k == -d:
            previous_k = k + 1

        elif k == d:
            previous_k = k - 1

        elif v.get(k - 1, -1) < v.get(k + 1, -1):
            previous_k = k + 1

        else:
            previous_k = k - 1

        previous_x = trace[d - 1].get(previous_k, 0)
        previous_y = previous_x - previous_k

        # ----------------------------------------------------
        # Everything between the previous point and the
        # current point on the diagonal is a snake of equal
        # elements.
        # ----------------------------------------------------

        while x > previous_x and y > previous_y:
            x -= 1
            y -= 1
            operations.append(("equal", a[x]))

        # ----------------------------------------------------
        # One non-diagonal move remains:
        #
        # x changed -> deletion
        # y changed -> insertion
        # ----------------------------------------------------

        if x == previous_x:
            # We moved in the y direction.
            y -= 1
            operations.append(("insert", b[y]))

        else:
            # We moved in the x direction.
            x -= 1
            operations.append(("delete", a[x]))

    # There can still be equal elements before the first edit.
    while x > 0 and y > 0:
        x -= 1
        y -= 1
        operations.append(("equal", a[x]))

    # Remaining prefix on either side.
    while x > 0:
        x -= 1
        operations.append(("delete", a[x]))

    while y > 0:
        y -= 1
        operations.append(("insert", b[y]))

    # We built the answer backwards.
    operations.reverse()

    return operations


# ============================================================
# Part A
# ============================================================

def format_line_diff(operations):
    """
    Convert Myers operations into Part A output.

    Prefix:
        ' ' = keep
        '-' = delete
        '+' = insert

    The assignment requires deletes before inserts inside
    every change block.
    """

    output = []

    i = 0

    while i < len(operations):

        operation, value = operations[i]

        # ----------------------------------------------------
        # Keep
        # ----------------------------------------------------

        if operation == "equal":
            output.append(b" " + value + b"\n")
            i += 1
            continue

        # ----------------------------------------------------
        # Change block:
        #
        # Collect consecutive deletes and inserts.
        # ----------------------------------------------------

        deletes = []
        inserts = []

        while i < len(operations) and operations[i][0] != "equal":

            operation, value = operations[i]

            if operation == "delete":
                deletes.append(value)
            else:
                inserts.append(value)

            i += 1

        # Delete lines first.
        for value in deletes:
            output.append(b"-" + value + b"\n")

        # Then insert lines.
        for value in inserts:
            output.append(b"+" + value + b"\n")

    return output


# ============================================================
# Part B - Character ranges
# ============================================================

def changed_ranges(old_line, new_line):
    """
    Find the minimum changed character ranges between two
    Unicode strings.

    Myers is run on Unicode code points because Python string
    iteration works in terms of Unicode code points.

    Returns:
        old_ranges
        new_ranges

    Each range is represented as (start, end), where end is
    exclusive.
    """

    old_chars = list(old_line)
    new_chars = list(new_line)

    operations = myers_diff(old_chars, new_chars)

    old_position = 0
    new_position = 0

    old_changed = []
    new_changed = []

    # Current changed range starts.
    old_start = None
    new_start = None

    def finish_old():
        nonlocal old_start

        if old_start is not None:
            old_changed.append((old_start, old_position))
            old_start = None

    def finish_new():
        nonlocal new_start

        if new_start is not None:
            new_changed.append((new_start, new_position))
            new_start = None

    for operation, value in operations:

        if operation == "equal":

            finish_old()
            finish_new()

            old_position += 1
            new_position += 1

        elif operation == "delete":

            if old_start is None:
                old_start = old_position

            old_position += 1

        elif operation == "insert":

            if new_start is None:
                new_start = new_position

            new_position += 1

    # Finish ranges at the end.
    finish_old()
    finish_new()

    return old_changed, new_changed


def format_ranges(ranges):
    """
    Convert:
        [(3, 5), (9, 12)]

    into:
        3-5,9-12

    Empty list becomes:
        .
    """

    if not ranges:
        return "."

    return ",".join(f"{start}-{end}" for start, end in ranges)


def build_highlight_output(old_lines, new_lines, operations):
    """
    Build Part B output.

    First print the normal Part A diff.

    Then, for every changed block:
        - pair 1st deletion with 1st insertion
        - pair 2nd deletion with 2nd insertion
        - etc.

    A '?' line is printed after each paired '+' line.
    """

    output = []

    i = 0

    while i < len(operations):

        operation, value = operations[i]

        # ----------------------------------------------------
        # Keep line
        # ----------------------------------------------------

        if operation == "equal":
            output.append(b" " + value + b"\n")
            i += 1
            continue

        # ----------------------------------------------------
        # Change block
        # ----------------------------------------------------

        deletes = []
        inserts = []

        while i < len(operations) and operations[i][0] != "equal":

            operation, value = operations[i]

            if operation == "delete":
                deletes.append(value)
            else:
                inserts.append(value)

            i += 1

        # ----------------------------------------------------
        # Output all deleted lines first.
        # ----------------------------------------------------

        for value in deletes:
            output.append(b"-" + value + b"\n")

        # ----------------------------------------------------
        # Output inserted lines.
        #
        # Pair deletion #1 with insertion #1, etc.
        # ----------------------------------------------------

        pair_count = min(len(deletes), len(inserts))

        for index, value in enumerate(inserts):

            output.append(b"+" + value + b"\n")

            if index < pair_count:

                old_line = deletes[index]
                new_line = value

                # Part B changed lines are guaranteed to be
                # valid UTF-8.
                old_text = old_line.decode("utf-8")
                new_text = new_line.decode("utf-8")

                old_ranges, new_ranges = changed_ranges(
                    old_text,
                    new_text
                )

                range_line = (
                    "? "
                    + format_ranges(old_ranges)
                    + " | "
                    + format_ranges(new_ranges)
                    + "\n"
                )

                output.append(range_line.encode("utf-8"))

    return output


# ============================================================
# Command handlers
# ============================================================

def run_lines(path_a, path_b):
    """
    Execute:
        program lines A B
    """

    old_lines = read_bytes_lines(path_a)
    new_lines = read_bytes_lines(path_b)

    if old_lines is None or new_lines is None:
        print(
            "Error: could not read input file",
            file=sys.stderr
        )
        return 2

    operations = myers_diff(old_lines, new_lines)

    output = format_line_diff(operations)

    # stdout must contain only the diff.
    sys.stdout.buffer.write(b"".join(output))

    return 0


def run_highlight(path_a, path_b):
    """
    Execute:
        program highlight A B
    """

    old_lines = read_bytes_lines(path_a)
    new_lines = read_bytes_lines(path_b)

    if old_lines is None or new_lines is None:
        print(
            "Error: could not read input file",
            file=sys.stderr
        )
        return 2

    operations = myers_diff(old_lines, new_lines)

    output = build_highlight_output(
        old_lines,
        new_lines,
        operations
    )

    sys.stdout.buffer.write(b"".join(output))

    return 0


# ============================================================
# Main
# ============================================================

def main():
    """
    Expected command:

        python src/main.py lines A B
        python src/main.py highlight A B
    """

    if len(sys.argv) != 4:
        print(
            "Usage: python src/main.py "
            "<lines|highlight> A B",
            file=sys.stderr
        )
        return 2

    command = sys.argv[1]
    path_a = sys.argv[2]
    path_b = sys.argv[3]

    if command == "lines":
        return run_lines(path_a, path_b)

    if command == "highlight":
        return run_highlight(path_a, path_b)

    print(
        "Error: command must be 'lines' or 'highlight'",
        file=sys.stderr
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())